### ISSUE TITLE
An error dialog occurs when debugging one python project

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-azurefunctions#1006]
**OS:** Windows
**Node.js:** 10.13.0
**Build Version**: [20190218.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3313&view=results)

**Repro Steps:**
1. Create a new python project -> Create a function with HTTP trigger template.
2. Debug.

**Expect:**
Debug successfully.

**Actual:**
An error dialog occurs.
![image](https://user-images.githubusercontent.com/41351993/53001389-6dccf280-3465-11e9-9fa9-4581644c2e69.png)

**Comment by EricJizbaMSFT** [comment]
@v-xianya Please copy the logs of the func: host start task

**Comment by v-xianya** [comment]
Hi @EricJizbaMSFT Here is the logs of the func: host start task. 

Http Functions:

        HttpTrigger: [GET,POST] http://localhost:7071/api/HttpTrigger

[2/20/2019 1:18:21 AM] Host lock lease acquired by instance ID '0000000000000000000000007E0B18AA'.
[2/20/2019 1:18:56 AM] **Language Worker Process exited.**
[2/20/2019 1:18:56 AM] **The operation has timed out.**
[2/20/2019 1:18:56 AM] Starting language worker process:python  C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py --default --host 127.0.0.1 --port 9091 --wait "C:\Users\AzureTest\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 1615 --workerId c6714824-4c35-495b-8d21-201e60cb157b --requestId f7afd152-9d33-477a-aada-1b5ef9133008 --grpcMaxMessageLength 134217728
[2/20/2019 1:18:56 AM] python process with Id=10036 started
[2/20/2019 1:18:56 AM] Starting language worker process:python  C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py --default --host 127.0.0.1 --port 9091 --wait "C:\Users\AzureTest\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 1615 --workerId 3e572662-0eeb-4c5b-a19a-2985a557a573 --requestId ee5baf26-6bc5-4ebd-879e-23978872f048 --grpcMaxMessageLength 134217728
[2/20/2019 1:18:56 AM] python process with Id=4132 started
[2/20/2019 1:19:00 AM] Traceback (most recent call last):
[2/20/2019 1:19:00 AM]   File "C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\ptvsd_launcher.py", line 45, in <module>
[2/20/2019 1:19:00 AM]     main(ptvsdArgs)
[2/20/2019 1:19:00 AM]   File "C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\__main__.py", line 348, in main
[2/20/2019 1:19:00 AM]     run()
[2/20/2019 1:19:00 AM]   File "C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\__main__.py", line 244, in run_file
[2/20/2019 1:19:00 AM]     setup_connection()
[2/20/2019 1:19:00 AM]   File "C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\__main__.py", line 237, in setup_connection
[2/20/2019 1:19:00 AM]     daemon = ptvsd._remote.enable_attach(addr)
[2/20/2019 1:19:00 AM]   File "C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\_remote.py", line 98, in enable_attach
[2/20/2019 1:19:00 AM]   File "C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 1658, in settrace[2/20/2019 1:19:00 AM]     stop_at_frame,
t)  # Note: connect ca\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 170n raise error.ort)  # Note: connect ca\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 170n raise error.ort)  # Note: connect can raise error.ort)  # Note: connect can raise error.ort)  # Note: connect can raise error.ort)  # Note: connect can raise error.ort)  # Note: connect can raise error.
[2/20/2019 1:19:00 AM]   File "C:\Users\AzureTest\.vscode-insiders\extensions\ms-python.python-2019.1.0\pythonFiles\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 687\lib\python\ptvsd\_vendored\pydevd\pydevd.py", line 687, in connect[2/20/2019 1:19:00 AM] **Language Worker Process exited.**
[2/20/2019 1:19:00 AM] **python exited with code 1
     debugger.connect(host, port)  # Note: connect can raise error.**
[2/20/2019 1:19:00 AM]     s = start_client(host, port)
[2/20/2019 1:19:36 AM] **Language Worker Process exited.**
[2/20/2019 1:19:36 AM] **The operation has timed out.**

**Comment by EricJizbaMSFT** [comment]
Hmm interesting I wonder if that port is blocked/busy for some reason on your machine. Can you change the port in your `.vscode/launch.json` file and try again? (Maybe 9092 instead of 9091)

Also - what version of the func cli do you have?

**Comment by v-xianya** [comment]
Thanks for your sharing. Show the same error after changing the port value to 9092.
func version : 2.4.317

**Comment by EricJizbaMSFT** [comment]
@v-xianya have you successfully debugged python functions on this machine before? I'm wondering if this is a machine-config problem or if something changed in our extension. I still can't repro this

**Comment by v-xianya** [comment]
@EricJizbaMSFT Thanks for your updates.
Verified on build [20190227.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3645&view=results). This issue doesn't reproduce.

**Comment by EricJizbaMSFT** [comment]
@v-xianya thanks for checking
