### ISSUE TITLE
"Failed to create terminal for task func: extensions install" after Ctrl + c

### ISSUE THREAD

**Issue by mhoeger** [Microsoft/vscode-azurefunctions#1019]
I'm running into errors with VS Code tasks whenever I use Ctrl + c to kill a running task. (This is with the upcoming TypeScript .vscode configurations)

Steps:
 - Create new TypeScript function app
 - Add TypeScript function (ex: HttpTrigger)
 - Press F5
 - At this point, everything is ok (see Figure 1)
 - Press Ctrl + c and then enter to kill the tasks that were running
 - Press F5
 - Errors appear (see Figure 2 and 3) and console output from another attempt:

```
[2019-02-21 16:48:49.724] [renderer1] [info] standard startup
[2019-02-21 16:53:18.725] [renderer1] [error] Cannot read property 'group' of undefined: TypeError: Cannot read property 'group' of undefined
    at e.createTerminal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3315:135)
    at l (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3309:58)
    at new Promise (<anonymous>)
    at e.executeInTerminal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3309:19)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3305:667
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Figure 1: Running Azure Functions!
<img width="1131" alt="screen shot 2019-02-21 at 5 35 35 pm" src="https://user-images.githubusercontent.com/8888531/53213816-37c37600-35ff-11e9-9d84-1ce0f3efdade.png">

Figure 2: Errors on second try
<img width="570" alt="screen shot 2019-02-21 at 5 30 19 pm" src="https://user-images.githubusercontent.com/8888531/53213887-6b9e9b80-35ff-11e9-82da-9a3080d264bb.png">

Figure 3:
<img width="1140" alt="screen shot 2019-02-21 at 5 30 47 pm" src="https://user-images.githubusercontent.com/8888531/53213936-90930e80-35ff-11e9-80bf-ee6c6664474f.png">

**Comment by EricJizbaMSFT** [comment]
Yeah I can repro this with "ctrl+c". But just FYI you can workaround this by using either the detach button at the top of VS Code (button on the right pictured here):
![screen shot 2019-02-21 at 7 16 20 pm](https://user-images.githubusercontent.com/11282622/53217583-5fb9d600-360d-11e9-9e6d-ad7f06ff765b.png)

Or if you hit the trash can on the task here:
![screen shot 2019-02-21 at 7 16 23 pm](https://user-images.githubusercontent.com/11282622/53217594-67797a80-360d-11e9-8864-a376e27284fc.png)

Those seem to work fine for me.

**Comment by EricJizbaMSFT** [comment]
This must've been fixed in VS Code. No longer repros for me - testing on 1.33.1
