### ISSUE TITLE
Unable to debug new function Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")

### ISSUE THREAD

**Issue by kurx78** [microsoft/vscode-azurefunctions#1547]
I'm having issues while testing a new Azure function, it seems that there is an issue with the function's job host

Http Functions:

        TestHttpTrigger: [GET,POST] http://localhost:7071/api/TestHttpTrigger

[10/4/2019 3:17:06 PM] System Log: { Log-Level: Information; Log-Message: The enforced concurrency level (pool size limit) is '1'. }
[10/4/2019 3:17:07 PM] Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
[10/4/2019 3:17:07 PM]    at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
[10/4/2019 3:17:07 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Messaging.MessagingStream.MoveNext() in C:\projects\azure-functions-powershell-worker\src\Messaging\MessagingStream.cs:line 34
[10/4/2019 3:17:07 PM]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessRequestLoop() in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 71
[10/4/2019 3:17:07 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.Main(String[] args) in C:\projects\azure-functions-powershell-worker\src\Worker.cs:line 42
[10/4/2019 3:17:07 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.<Main>(String[] args)
[10/4/2019 3:17:07 PM] Starting language worker process:dotnet  "C:\Users\gomezj5\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\Microsoft.Azure.Functions.PowerShellWorker.dll" --host 127.0.0.1 --port 57898 --workerId 4c3d7fbc-6ce1-4642-82c0-413836638f66 --requestId 2bbb9d37-065e-4354-8cf7-6d13762f9e3c --grpcMaxMessageLength 134217728
[10/4/2019 3:17:07 PM] dotnet process with Id=20984 started
[10/4/2019 3:17:08 PM] System Log: { Log-Level: Information; Log-Message: The enforced concurrency level (pool size limit) is '1'. }
[10/4/2019 3:17:08 PM] Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
[10/4/2019 3:17:08 PM]    at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
[10/4/2019 3:17:08 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Messaging.MessagingStream.MoveNext() in C:\projects\azure-functions-powershell-worker\src\Messaging\MessagingStream.cs:line 34
[10/4/2019 3:17:08 PM]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessRequestLoop() in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 71
[10/4/2019 3:17:08 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.Main(String[] args) in C:\projects\azure-functions-powershell-worker\src\Worker.cs:line 42
[10/4/2019 3:17:08 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.<Main>(String[] args)
[10/4/2019 3:17:08 PM] Starting language worker process:dotnet  "C:\Users\gomezj5\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\powershell\Microsoft.Azure.Functions.PowerShellWorker.dll" --host 127.0.0.1 --port 57898 --workerId e92458cc-c5a9-4f16-9527-2bcc1c979962 --requestId 23b6152b-521d-403a-ae80-1511b58e46d0 --grpcMaxMessageLength 134217728
[10/4/2019 3:17:08 PM] dotnet process with Id=21084 started
[10/4/2019 3:17:09 PM] System Log: { Log-Level: Information; Log-Message: The enforced concurrency level (pool size limit) is '1'. }
[10/4/2019 3:17:09 PM] Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
[10/4/2019 3:17:09 PM]    at Grpc.Core.Internal.ClientResponseStream`2.MoveNext(CancellationToken token)
[10/4/2019 3:17:09 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Messaging.MessagingStream.MoveNext() in C:\projects\azure-functions-powershell-worker\src\Messaging\MessagingStream.cs:line 34
[10/4/2019 3:17:09 PM]    at Microsoft.Azure.Functions.PowerShellWorker.RequestProcessor.ProcessRequestLoop() in C:\projects\azure-functions-powershell-worker\src\RequestProcessor.cs:line 71
[10/4/2019 3:17:09 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.Main(String[] args) in C:\projects\azure-functions-powershell-worker\src\Worker.cs:line 42
[10/4/2019 3:17:09 PM]    at Microsoft.Azure.Functions.PowerShellWorker.Worker.<Main>(String[] args)
[10/4/2019 3:17:09 PM] Exceeded language worker restart retry count for runtime:powershell. Shutting down Functions Host
[10/4/2019 3:17:09 PM] Stopping host...
[10/4/2019 3:17:09 PM] Stopping JobHost
[10/4/2019 3:17:09 PM] Job host stopped
[10/4/2019 3:17:10 PM] Host shutdown completed.
Application is shutting down...

Terminal will be reused by tasks, press any key to close it.

**Comment by EricJizbaMSFT** [comment]
@kurx78 does this repro if you just run `func host start` from the command line? You might have better luck filing an issue directly on the func cli, where those logs are coming from: https://github.com/Azure/azure-functions-core-tools
