### ISSUE TITLE
Failed to run Java HttpTrigger

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-azurefunctions#195]
Repro steps:
1. Create a new Java project
1. F5
1. Hit the default trigger url (http://localhost:7071/api/hello)
 
Expected: Success
Actual: Fail:
```
Http Functions:

        hello: http://localhost:7071/api/hello

info: Worker.Java.b39fcda4-51cd-47ff-a757-c1bf5bee59de[0]
      Microsoft Azure Functions Java Runtime [build 1.1-SNAPSHOT]
info: Worker.Java.b39fcda4-51cd-47ff-a757-c1bf5bee59de[0]
      [INFO] {com.microsoft.azure.webjobs.script.handler.MessageHandler.handle}: message generated by "class com.microsoft.azure.webjobs.script.rpc.messages.StartStream$Builder"
info: Worker.Java.b39fcda4-51cd-47ff-a757-c1bf5bee59de[0]
      Worker initialized
info: Worker.Java.b39fcda4-51cd-47ff-a757-c1bf5bee59de[0]
      f7a8746f-5f5f-428d-885d-4a85d530d951 - "/Users/ericjizba/TestRepos/5/target/azure-functions/5-1516988875298/5-1.0-SNAPSHOT.jar"::"com.function.Function.hello" loaded
[1/26/18 5:48:52 PM] Function started (Id=faaffd0d-ec34-45b3-81ff-f78b85e8ea1f)
[1/26/18 5:48:52 PM] Executing 'Functions.hello' (Reason='This function was programmatically called via the host APIs.', Id=faaffd0d-ec34-45b3-81ff-f78b85e8ea1f)
[1/26/18 5:48:52 PM] Java HTTP trigger processed a request.
[1/26/18 5:48:52 PM] A ScriptHost error has occurred
[1/26/18 5:48:52 PM] Exception while executing function: Functions.hello. System.Private.CoreLib: Result:
[1/26/18 5:48:52 PM] Exception:
[1/26/18 5:48:52 PM] Stack: java.lang.reflect.InvocationTargetException
[1/26/18 5:48:52 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[1/26/18 5:48:52 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[1/26/18 5:48:52 PM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[1/26/18 5:48:52 PM]    at java.lang.reflect.Method.invoke(Method.java:498)
[1/26/18 5:48:52 PM]    at com.microsoft.azure.webjobs.script.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:19)
[1/26/18 5:48:52 PM]    at com.microsoft.azure.webjobs.script.broker.JavaMethodExecutor.execute(JavaMethodExecutor.java:34)
[1/26/18 5:48:52 PM]    at com.microsoft.azure.webjobs.script.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:40)
[1/26/18 5:48:52 PM]    at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
[1/26/18 5:48:52 PM]    at com.microsoft.azure.webjobs.script.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
[1/26/18 5:48:52 PM]    at com.microsoft.azure.webjobs.script.handler.MessageHandler.handle(MessageHandler.java:41)
[1/26/18 5:48:52 PM]    at com.microsoft.azure.webjobs.script.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:84)
[1/26/18 5:48:52 PM]    at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[1/26/18 5:48:52 PM]    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[1/26/18 5:48:52 PM]    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[1/26/18 5:48:52 PM]    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[1/26/18 5:48:52 PM]    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[1/26/18 5:48:52 PM] Caused by: java.lang.NullPointerException
[1/26/18 5:48:52 PM]    at com.function.Function.hello(Function.java:24)
[1/26/18 5:48:52 PM]    ... 16 more
[1/26/18 5:48:52 PM] .
```

**Comment by EricJizbaMSFT** [comment]
According to @jdneo this is due to an outdated functions runtime. Updating the runtime fixed it for me:
```
npm i -g azure-functions-core-tools@core --unsafe-perm
```
I posted this issue for two reasons:
1. In case other users run into it
1. We should consider adding a better warning or error message if the func runtime version is incompatible
