### ISSUE TITLE
Error when loading function templates

### ISSUE THREAD

**Issue by raedaj** [microsoft/vscode-azurefunctions#2020]
I'm getting an error when I create a new function project after I select C#. I'm using VS Code on macOS. Latest VS Code and lastest Azure Tools extensions are installed

The issue text9:04:00 PM: Failed to get latest templates: Command "dotnet '/Users/Raed/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.21.0/resources/dotnetJsonCli/netcoreapp3.0/Microsoft.TemplateEngine.JsonCli.dll' --require '/Users/Raed/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~3.nupkg' --require '/Users/Raed/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~3.nupkg' --operation list" failed with exit code "null":
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/Users/Raed/.templateengine/AzureFunctions-VSCodeExtension/1.0.0/en-US.templatecache.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.WriteAllText(String path, String value)
   at Microsoft.TemplateEngine.Edge.Paths.WriteAllText(String path, String value)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.WriteTemplateCache(IList`1 templates, String locale, Boolean hasContentChanges)
   at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCacheForLocale(String locale, String existingCacheVersion)
   at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCaches(String existingCacheVersion)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
   at Microsoft.TemplateEngine.JsonCli.Installer.InstallPackages(IEnumerable`1 installationRequests, IList`1 nuGetSources) in /Users/erijiz/Repos/vscode-azurefunctions/tools/JsonCli/src/Installer.cs:line 77
   at Microsoft.TemplateEngine.JsonCli.Program.Main(String[] args)

9:04:00 PM: Failed to get backup templates: Command "dotnet '/Users/Raed/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.21.0/resources/dotnetJsonCli/netcoreapp3.0/Microsoft.TemplateEngine.JsonCli.dll' --require '/Users/Raed/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~3.nupkg' --require '/Users/Raed/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~3.nupkg' --operation list" failed with exit code "null":
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/Users/Raed/.templateengine/AzureFunctions-VSCodeExtension/1.0.0/en-US.templatecache.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.WriteAllText(String path, String value)
   at Microsoft.TemplateEngine.Edge.Paths.WriteAllText(String path, String value)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.WriteTemplateCache(IList`1 templates, String locale, Boolean hasContentChanges)
   at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCacheForLocale(String locale, String existingCacheVersion)
   at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCaches(String existingCacheVersion)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
   at Microsoft.TemplateEngine.JsonCli.Installer.InstallPackages(IEnumerable`1 installationRequests, IList`1 nuGetSources) in /Users/erijiz/Repos/vscode-azurefunctions/tools/JsonCli/src/Installer.cs:line 77
   at Microsoft.TemplateEngine.JsonCli.Program.Main(String[] args)

9:04:00 PM: Error: Failed to get latest templates: Command "dotnet '/Users/Raed/.vscode/extensions/ms-azuretools.vscode-azurefunctions-0.21.0/resources/dotnetJsonCli/netcoreapp3.0/Microsoft.TemplateEngine.JsonCli.dll' --require '/Users/Raed/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/itemTemplates-~3.nupkg' --require '/Users/Raed/Library/Application Support/Code/User/globalStorage/ms-azuretools.vscode-azurefunctions/dotnetTemplates/projectTemplates-~3.nupkg' --operation list" failed with exit code "null":
Unhandled exception. System.UnauthorizedAccessException: Access to the path '/Users/Raed/.templateengine/AzureFunctions-VSCodeExtension/1.0.0/en-US.templatecache.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.CreateFile(String path)
   at Microsoft.TemplateEngine.Utils.InMemoryFileSystem.WriteAllText(String path, String value)
   at Microsoft.TemplateEngine.Edge.Paths.WriteAllText(String path, String value)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.WriteTemplateCache(IList`1 templates, String locale, Boolean hasContentChanges)
   at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCacheForLocale(String locale, String existingCacheVersion)
   at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCaches(String existingCacheVersion)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
   at Microsoft.TemplateEngine.JsonCli.Installer.InstallPackages(IEnumerable`1 installationRequests, IList`1 nuGetSources) in /Users/erijiz/Repos/vscode-azurefunctions/tools/JsonCli/src/Installer.cs:line 77
   at Microsoft.TemplateEngine.JsonCli.Program.Main(String[] args)

 was copied to the clipboard.  Please paste it into this window.

**Comment by EricJizbaMSFT** [comment]
This seems like the most relevant part of the logs. Any idea why it wouldn't have access?

> Unhandled exception. System.UnauthorizedAccessException: Access to the path '/Users/Raed/.templateengine/AzureFunctions-VSCodeExtension/1.0.0/en-US.templatecache.json' is denied.
