### ISSUE TITLE
Worker was unable to load function (...) : 'Error: Cannot find module (...)

### ISSUE THREAD

**Issue by noobii** [microsoft/vscode-azurefunctions#2066]
Hi, 

We have been setting up a project with Azure functions (runtime ~3) and TypeScript/NodeJS.
We now have an issue with an import that only fails when starting the function app (locally or on Azure). The compilation with `tsc` works fine.

```
[29.04.2020 20:53:04] Worker was unable to load function Events: 'Error: Cannot find module '@<removed>/common/models/common/eventValidation'
Require stack:
- C:\Users\<removed>\Workspace\Roro\back\dist\Events\index.js
- C:\Users\<removed>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js
- C:\Users\<removed>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\nodejsWorker.js'
[29.04.2020 20:53:04] Worker failed to function id 724571cf-b667-46b0-bb1f-7718cec172f3.
[29.04.2020 20:53:04] Result: Failure
Exception: Worker was unable to load function Events: 'Error: Cannot find module '@<removed>/common/models/common/eventValidation'
Require stack:
- C:\Users\<removed>\Workspace\<removed>\back\dist\Events\index.js
- C:\Users\<removed>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js
- C:\Users\<removed>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\nodejsWorker.js'
Stack: Error: Cannot find module '@<removed>/common/models/common/eventValidation'
Require stack:
- C:\Users\<removed>\Workspace\<removed>\back\dist\Events\index.js
- C:\Users\<removed>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js
- C:\Users\<removed>\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\nodejsWorker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\<removed>\Workspace\Roro\back\dist\Events\index.js:12:27)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19).`
```
The package is imported simply with `import { validateEvent } from '@<removed>/common/models/common/eventValidation';`

The content of compiled file is
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
function validateEvent(e, mustHaveId) {
    if (mustHaveId === void 0) { mustHaveId = false; }
    if (e === null || e === undefined)
        throw new Error('Event must be an object');
    if (mustHaveId && !e.id)
        throw new Error('Event must have id');
    if (!e.orgId || !e.siteId || !e.gateId || !e.deviceId)
        throw new Error('Event must have org, site, gate and device ids');
    if (!e.eventTime || !e.eventTimeZoneOffset)
        throw new Error('Event must have event time and timezone offset');
    // TODO add specific data validations
    switch (e.dataType) {
        case 'x':
            break;
        case 'y':
            break;
        case 'z':
            break;
        default:
            throw new Error("Event type '" + e.dataType + "' not supported");
    }
}
exports.validateEvent = validateEvent;
```

Other imports from the same package are imported just fine.
I can't make sense of it 😢

**Comment by noobii** [comment]
Found issue with TypeScript compilation of the library that was imported. 
Sorry about that!
