### ISSUE TITLE
Error when deploying a Function App from Visual Studio Code to Azure

### ISSUE THREAD

**Issue by tedescomicchidev** [microsoft/vscode-azurefunctions#2110]
Does this occur consistently? Yes
Repro steps:

1. Create a new Function App via VS Code
2. Deploy a local Function App to the new Cloud one.

Action: azureFunctions.deploy
Error type: Error
Error Message: Failed to deploy path that does not exist: /home/vsonline/workspace/JavaFunctionSDKSample/fabrikam-functions/target/azure-functions/fabrikam-functions-20200516220016913

Version: 0.22.1
OS: linux
OS Release: 5.3.0-1020-azure
Product: Visual Studio Code
Product Version: 1.45.0
Language: en-GB

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:281:26571
fulfilled extension.bundle.js:281:26075
```

</details>

**Comment by EricJizbaMSFT** [comment]
@tedescomicchidev Did the mvn package task succeed before you deployed? That's what creates the path mentioned in the error message. You should see an error message when you deploy with an option to "Deploy Anyway". Instead of clicking that "Deploy Anyway", take a look at the logs that should have popped up on screen

**Comment by tedescomicchidev** [comment]
After starting a deployment I get following logs from "Azure Functions Output":
7:28:37 PM mitedescMigrosFunctionTest15: Stopping app...
7:28:40 PM mitedescMigrosFunctionTest15: Creating zip package...

And following error appears on "Log (Windows)":
[2020-05-18 21:27:39.916] [window] [warning] Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
[2020-05-18 21:28:17.328] [window] [error] [object Event]: Error: [object Event]
    at Object.t [as ensureError] (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:7:522)
    at s._createLoadError (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:27:162)
    at s._onLoadError (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:27:281)
    at i (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:29:20)
    at Object.errorback (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:29:383)
    at e.triggerErrorback (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:13:955)
    at https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:13:659
    at HTMLScriptElement.i (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:14:176)
[2020-05-18 21:28:33.620] [window] [error] The request (id: 15, method: 'textDocument/hover') has been cancelled: Error: The request (id: 15, method: 'textDocument/hover') has been cancelled
    at /home/vsonline/.vscode-remote/extensions/redhat.java-0.61.0/dist/extension.js:1:73458
    at /home/vsonline/.vscode-remote/extensions/redhat.java-0.61.0/dist/extension.js:1:73752
    at Immediate.<anonymous> (/home/vsonline/.vscode-remote/extensions/redhat.java-0.61.0/dist/extension.js:1:74113)
    at processImmediate (internal/timers.js:439:21)
[2020-05-18 21:28:38.547] [window] [error] Cannot read property 'objectMode' of undefined: TypeError: Cannot read property 'objectMode' of undefined
    at WriteStream.Writable.write (_stream_writable.js:278:24)
    at Archiver.ondata (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:21473)
    at Archiver.emit (events.js:200:13)
    at addChunk (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:15705)
    at readableAddChunk (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:15509)
    at Archiver.Readable.push (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:16385)
    at Archiver.Transform.push (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:41185)
    at Archiver.afterTransform (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:40159)
    at Archiver._transform (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:241:4523)
    at Archiver.Transform._read (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:41670)
    at Archiver.Transform._write (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:41501)
    at doWrite (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:30522)
    at writeOrBuffer (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:33993)
    at Archiver.Writable.write (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:34026)
    at e.exports.ondata (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:58028)
    at e.exports.emit (events.js:200:13)
    at addChunk (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:52260)
    at readableAddChunk (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:52048)
    at e.exports.Readable.push (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:52944)
    at e.exports.Transform.push (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:75100)
    at e.exports.afterTransform (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:73979)
    at e.exports.u._transform (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:48263)
    at e.exports.Transform._read (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:75604)
    at e.exports.Transform._write (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:75442)
    at doWrite (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:64643)
    at writeOrBuffer (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:68134)
    at e.exports.Writable.write (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:68167)
    at e.exports.u.write (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:49181)
    at e.exports.d._writeLocalFileHeader (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:265:9422)
    at e.exports.d._appendStream (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:265:4847)
    at e.exports.u.entry (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:164:48807)
    at e.exports.u.entry (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:265:1454)
    at Zip.append (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:257:258)
    at Archiver._moduleAppend (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:241:1786)
    at Archiver._onQueueTask (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:241:3927)
    at /home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:241:40304
    at Object.process (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:241:33639)
    at /home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:241:32719
    at Immediate.<anonymous> (/home/vsonline/.vscode-remote/extensions/ms-azuretools.vscode-azurefunctions-0.22.1/dist/extension.bundle.js:241:21193)
    at processImmediate (internal/timers.js:439:21)

**Comment by tedescomicchidev** [comment]
Additional information: If I Deploy the same local Function to a new Azure Function instead of an existing, this works well.

**Comment by tedescomicchidev** [comment]
Also I get this error when the "Deploy action" gets called:
[2020-05-19 10:50:26.790] [window] [error] [object Event]: Error: [object Event]
    at Object.t [as ensureError] (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:7:522)
    at s._createLoadError (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:27:162)
    at s._onLoadError (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:27:281)
    at i (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:29:20)
    at Object.errorback (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:29:383)
    at e.triggerErrorback (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:13:955)
    at https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:13:659
    at HTMLScriptElement.i (https://online.visualstudio.com/workbench-page/web-standalone/stable-d69a79b/out/vs/loader.js:14:176)

**Comment by tedescomicchidev** [comment]
Hi - any updates?

**Comment by EricJizbaMSFT** [comment]
Hmm those logs don't mean much to me. You got them from the "Azure Functions" output window?

When you deploy, it should run a "mvn" task. I believe the task output will pop up automatically. Please copy the logs from that as well. If it doesn't pop up, look for "mvn" in the "terminal" pane
