### ISSUE TITLE
 Unexpected token error when deploying Azure Functions with VS Code

### ISSUE THREAD

**Issue by Anmol007** [microsoft/vscode-azurefunctions#2464]
Does this occur consistently? Yes
Repro steps:

1. Create a ServiceBusTopicTrigger function
2. Deploy with VS Code

Action: azureFunctions.deploy
Error type: PARSE_ERROR
Error Message: Error "SyntaxError: Unexpected token S in JSON at position 0" occurred while parsing the response body - Service Unavailable.

Version: 0.24.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.50.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:48:94460
errorHandler extension.bundle.js:48:1289404
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please add repro steps

**Comment by Anmol007** [comment]
> Please add repro steps

@nturinski I have already added minimal repro steps, here's the each step in detail:
1. Install the Azure Function extension in VS code.
2. After installation, select the Azure icon on the Activity bar.
3. From Azure: Functions, select the Create Function icon.
4. Select the folder for your function app project, and then Select a Python for your function project.
5. Select the Azure Service Bus topic trigger function template
6. Provide the function name, topic name from which messages will be read and subscription name.
7. Assign the connection string to the connection value in function.json
8. Deploy to Function App

**Comment by pietervincken** [comment]
Ran into the same issue today. I'm behind a corporate proxy, but I've already set the proxy settings to override and I do see the service plan to deploy the app to.

**Comment by Zurlys** [comment]
Ran into same problem today

`9:18:17 AM XXX: Starting deployment...
9:18:18 AM XXX: Creating zip package...
9:18:18 AM XXX: Zip package size: 2.22 kB
9:20:49 AM: Error: Error "SyntaxError: Unexpected token S in JSON at position 0" occurred while parsing the response body - Service Unavailable.`

**Comment by LightLow** [comment]
Hi I have the same problem with the error:

Provide more info here, no issue if I deploy to existing Azure Functions (created before 18th November 2020).
But trigger same error when I create a new Azure Functions (at 2nd December 2020) and deploy the same python script.

**Comment by pltchuong** [comment]
I'm having the same issue, this is what I see from command line with debug enabled.

```
Azure.Functions.Cli.Common.CliException: Error Uploading archive... (ServiceUnavailable).
Server Response: Service Unavailable
   at Azure.Functions.Cli.Helpers.PublishHelper.CheckResponseStatusAsync(HttpResponseMessage response, String message) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\PublishHelper.cs:line 98
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PerformServerSideBuild(Site functionApp, Func`1 zipFileFactory, Func`2 deploymentStatusPollTask) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 756
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PerformAppServiceRemoteBuild(Func`1 zipStreamFactory, Site functionApp) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 480
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.HandleLinuxDedicatedPublish(Site functionApp, Func`1 zipStreamFactory) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 454
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 351
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 171
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

My current version:
```
Azure Functions Core Tools
Core Tools Version:       3.0.3160 Commit hash: 00aa7f43cc5c5f15241b5e6e5363256f19ceb990
Function Runtime Version: 3.0.14916.0
```

**Comment by pltchuong** [comment]
turns out this issue happened because I used Terraform to create Function App using `resource azurerm_function_app`. For some reasons Terraform doesn't create some needed files like `host.json`, so when you accessing to https://abcxyz.azurewebsites.net/ you will just see "Service Unavailable" instead of a welcome page "Your Functions 3.0 app is up and running"
