### ISSUE TITLE
Error: Parse Error: Expected HTTP/

### ISSUE THREAD

**Issue by janmechtel** [microsoft/vscode-azurefunctions#2649]
## Background: 
- I'm using an node-fetch azure function as a mini proxy
- I have an exception is thrown inside a the "simple" node-fetch that only occurs only for certain requests
- I want to debug the request further and researched that https://httptoolkit.tech/ might help to see which requests node-fetch is actually sending

# Problem

`func start` fails with:

> [2021-01-29T21:09:17.759Z]   details: 'Received http2 header with status: 502'

Inside the HTTP toolkit i can see the response body:

**Error: Parse Error: Expected HTTP/**

I found this issue which mentions to turn off VPN: https://github.com/microsoft/vscode-azurefunctions/issues/2327
that doesn't help in my situation.

Any ideas?

## Logs

The request header shown inside http toolkit is this

> METHOD: POST
> URL http://127.0.0.1:59713/AzureFunctionsRpcMessages.FunctionRpc/EventStream
> HEADERS
> :authority: 127.0.0.1:59713
> :method: POST
> :path: /AzureFunctionsRpcMessages.FunctionRpc/EventStream
> :scheme: http
> accept-encoding: identity,gzip
> content-type: application/grpc
> grpc-accept-encoding: identity,deflate,gzip
> te: trailers
> user-agent: grpc-node/1.24.2 grpc-c/8.0.0 (windows; chttp2; ganges)

Full output from `func start`:
>  at Object.module.exports.exports.createStatusError (C:\Users\ampelmann\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:980:15)
> [2021-01-29T21:09:17.730Z]     at ClientDuplexStream._emitStatusIfDone (C:\Users\ampelmann\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7585:26)
> [2021-01-29T21:09:17.732Z]     at ClientDuplexStream._receiveStatus (C:\Users\ampelmann\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:7563:8)
> [2021-01-29T21:09:17.734Z]     at Object.onReceiveStatus (C:\Users\ampelmann\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:22846:15)
> [2021-01-29T21:09:17.736Z]     at InterceptingListener.module.exports.InterceptingListener._callNext (C:\Users\ampelmann\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:22103:42)
> [2021-01-29T21:09:17.743Z]     at InterceptingListener.module.exports.InterceptingListener.onReceiveStatus (C:\Users\ampelmann\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:22153:8)
> [2021-01-29T21:09:17.744Z]     at C:\Users\ampelmann\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\worker-bundle.js:22662:18 {
> [2021-01-29T21:09:17.746Z]   code: 1,
> [2021-01-29T21:09:17.749Z]   metadata: Metadata {
> [2021-01-29T21:09:17.752Z]     _internal_repr: { 'grpc-status': [Array], 'grpc-message': [Array] },
> [2021-01-29T21:09:17.754Z]     flags: 0
> [2021-01-29T21:09:17.757Z]   },
> [2021-01-29T21:09:17.759Z]   details: 'Received http2 header with status: 502'
> [2021-01-29T21:09:17.762Z] }

https://github.com/microsoft/vscode-azurefunctions/issues/2327

**Comment by janmechtel** [comment]
I've decided to go another route and replace the proxy function with something non-node

**Comment by janmechtel** [comment]
I've replaced the node azure function with c# script and use HTTPClient to make the request, but same problem. 

I'd love to be able to intercept all outgoing/incoming HTTP from the function host.
