### ISSUE TITLE
VS code azure powershell function debugging issue - Omnisharp Json Rpc exception

### ISSUE THREAD

**Issue by lavibhatnagar** [microsoft/vscode-azurefunctions#3223]
Environment: 
VS Code version: 1.68.0
C# Extension version: 1.25.0
Azure Core tools: v4
Powershell version: 7

Error:
![image](https://user-images.githubusercontent.com/5319479/174055673-46a3f5d9-caee-4066-b0e1-b24928110ec5.png)

Steps to reproduce:

1. Create azure powershell function
2. Put a breakpoint anywhere and hit F5
3. See error

Things Tried:
1. uninstalling c# extension
2. installing c# extension
3. changed c# extension version
4. removed extensionBundle section from host.json

**Comment by nturinski** [comment]
Thanks for reporting this.  We can also reproduce this issue, so we'll start investigating.

Do you have any idea when this started occurring? Or has the debugger never worked for Powershell 7?

**Comment by lavibhatnagar** [comment]
@nturinski i have no idea since when this issue started occurring, i encountered this issue on 15 june.

**Comment by alexweininger** [comment]
Could you provide any output from the Powershell Extension Logs and the Omnisharp Log output channels?

Based on [this comment](https://github.com/OmniSharp/omnisharp-vscode/issues/5279#issuecomment-1158099871), I got it working by adding an empty main.cs file to the root of my workspace.

**Comment by adrwh** [comment]
I created a fresh Function from scratch from VS Code and ran F5, heres the output.

```
 *  Executing task: func host start 


Azure Functions Core Tools
Core Tools Version:       4.0.4590 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.5.2.18383


Functions:

        HttpTrigger1: [GET,POST] http://localhost:7071/api/HttpTrigger1

For detailed output, run func with --verbose flag.
[2022-07-08T14:24:18.668Z] Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
[2022-07-08T14:24:18.668Z]  ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSSysLogProvider' threw an exception.
[2022-07-08T14:24:18.669Z]  ---> System.DllNotFoundException: Unable to load shared library 'libpsl-native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibpsl-native, 0x0001): tried: 'liblibpsl-native' (no such file), '/usr/local/lib/liblibpsl-native' (no such file), '/usr/lib/liblibpsl-native' (no such file), '/Volumes/dev/functest/liblibpsl-native' (no such file)
[2022-07-08T14:24:18.669Z]    at System.Management.Automation.Tracing.NativeMethods.OpenLog(IntPtr ident, SysLogPriority facility)
[2022-07-08T14:24:18.669Z]    at System.Management.Automation.Tracing.SysLogProvider..ctor(String applicationId, PSLevel level, PSKeyword keywords, PSChannel channels)
[2022-07-08T14:24:18.669Z]    at System.Management.Automation.Tracing.PSSysLogProvider..cctor()
[2022-07-08T14:24:18.669Z]    --- End of inner exception stack trace ---
[2022-07-08T14:24:18.669Z]    at System.Management.Automation.Tracing.PSSysLogProvider..ctor()
[2022-07-08T14:24:18.669Z]    at System.Management.Automation.Tracing.PSEtwLog..cctor()
[2022-07-08T14:24:18.669Z]    --- End of inner exception stack trace ---
[2022-07-08T14:24:18.669Z]    at System.Management.Automation.Tracing.PSEtwLog.LogOperationalInformation(PSEventId id, PSOpcode opcode, PSTask task, PSKeyword keyword, Object[] args)
[2022-07-08T14:24:18.669Z]    at System.Management.Automation.Remoting.RemoteSessionNamedPipeServer.ProcessListeningThread(Object state)
[2022-07-08T14:24:18.669Z]    at System.Threading.Thread.StartCallback()
[2022-07-08T14:24:18.718Z] Language Worker Process exited. Pid=29738.
[2022-07-08T14:24:18.718Z] dotnet exited with code 134 (0x86). Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
[2022-07-08T14:24:18.774Z] Failed to start a new language worker for runtime: powershell.
[2022-07-08T14:24:18.774Z] System.Private.CoreLib: A task was canceled.
[2022-07-08T14:24:18.961Z] Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
[2022-07-08T14:24:18.961Z]  ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSSysLogProvider' threw an exception.
[2022-07-08T14:24:18.961Z]  ---> System.DllNotFoundException: Unable to load shared library 'libpsl-native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibpsl-native, 0x0001): tried: 'liblibpsl-native' (no such file), '/usr/local/lib/liblibpsl-native' (no such file), '/usr/lib/liblibpsl-native' (no such file), '/Volumes/dev/functest/liblibpsl-native' (no such file)
[2022-07-08T14:24:18.961Z]    at System.Management.Automation.Tracing.NativeMethods.OpenLog(IntPtr ident, SysLogPriority facility)
[2022-07-08T14:24:18.962Z]    at System.Management.Automation.Tracing.SysLogProvider..ctor(String applicationId, PSLevel level, PSKeyword keywords, PSChannel channels)
[2022-07-08T14:24:18.962Z]    at System.Management.Automation.Tracing.PSSysLogProvider..cctor()
[2022-07-08T14:24:18.962Z]    --- End of inner exception stack trace ---
[2022-07-08T14:24:18.962Z]    at System.Management.Automation.Tracing.PSSysLogProvider..ctor()
[2022-07-08T14:24:18.962Z]    at System.Management.Automation.Tracing.PSEtwLog..cctor()
[2022-07-08T14:24:18.962Z]    --- End of inner exception stack trace ---
[2022-07-08T14:24:18.962Z]    at System.Management.Automation.Tracing.PSEtwLog.LogOperationalInformation(PSEventId id, PSOpcode opcode, PSTask task, PSKeyword keyword, Object[] args)
[2022-07-08T14:24:18.962Z]    at System.Management.Automation.Remoting.RemoteSessionNamedPipeServer.ProcessListeningThread(Object state)
[2022-07-08T14:24:18.962Z]    at System.Threading.Thread.StartCallback()
[2022-07-08T14:24:18.995Z] Language Worker Process exited. Pid=29743.
[2022-07-08T14:24:18.995Z] dotnet exited with code 134 (0x86). Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
[2022-07-08T14:24:23.355Z] Host lock lease acquired by instance ID '00000000000000000000000021AF8539'.
[2022-07-08T14:24:29.296Z] Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
[2022-07-08T14:24:29.296Z]  ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSSysLogProvider' threw an exception.
[2022-07-08T14:24:29.296Z]  ---> System.DllNotFoundException: Unable to load shared library 'libpsl-native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibpsl-native, 0x0001): tried: 'liblibpsl-native' (no such file), '/usr/local/lib/liblibpsl-native' (no such file), '/usr/lib/liblibpsl-native' (no such file), '/Volumes/dev/functest/liblibpsl-native' (no such file)
[2022-07-08T14:24:29.296Z]    at System.Management.Automation.Tracing.NativeMethods.OpenLog(IntPtr ident, SysLogPriority facility)
[2022-07-08T14:24:29.296Z]    at System.Management.Automation.Tracing.SysLogProvider..ctor(String applicationId, PSLevel level, PSKeyword keywords, PSChannel channels)
[2022-07-08T14:24:29.296Z]    at System.Management.Automation.Tracing.PSSysLogProvider..cctor()
[2022-07-08T14:24:29.296Z]    --- End of inner exception stack trace ---
[2022-07-08T14:24:29.296Z]    at System.Management.Automation.Tracing.PSSysLogProvider..ctor()
[2022-07-08T14:24:29.296Z]    at System.Management.Automation.Tracing.PSEtwLog..cctor()
[2022-07-08T14:24:29.296Z]    --- End of inner exception stack trace ---
[2022-07-08T14:24:29.296Z]    at System.Management.Automation.Tracing.PSEtwLog.LogOperationalInformation(PSEventId id, PSOpcode opcode, PSTask task, PSKeyword keyword, Object[] args)
[2022-07-08T14:24:29.296Z]    at System.Management.Automation.Remoting.RemoteSessionNamedPipeServer.ProcessListeningThread(Object state)
[2022-07-08T14:24:29.297Z]    at System.Threading.Thread.StartCallback()
[2022-07-08T14:24:29.329Z] Language Worker Process exited. Pid=29750.
[2022-07-08T14:24:29.329Z] dotnet exited with code 134 (0x86). Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
[2022-07-08T14:24:29.329Z] Exceeded language worker restart retry count for runtime:powershell. Shutting down and proactively recycling the Functions Host to recover
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

**Comment by lavibhatnagar** [comment]
> {
>   "version": "0.2.0",
>   "configurations": [
>     {
>       "name": "PowerShell Launch Current File",
>       "type": "PowerShell",
>       "request": "launch",
>       "script": "${file}",
>       "cwd": "${file}"
>     },
>     {
>       "name": "Attach to PowerShell Functions",
>       "type": "PowerShell",
>       "request": "attach",
>       "customPipeName": "AzureFunctionsPSWorker",
>       "runspaceId": 1,
>       "preLaunchTask": "func: host start --powershell --verbose"
>     }
>   ]
> }

Tried same thing but i am still getting same error. reinstalled c# extension.
![image](https://user-images.githubusercontent.com/5319479/178012466-eeed6ce6-bcc4-447f-96e0-93ceeb8d116b.png)

**Comment by nturinski** [comment]
Hi all,

I was running into the `OmniSharp.Extensions.JsonRpc.RpcErrorException` as well. After installing [PowerShell 7.2](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#msi) however, it seems to be attaching correctly:

![image](https://user-images.githubusercontent.com/5290572/179100733-99fc8cd2-caac-4a9a-8158-42741b8215ea.png)


Note that `func host start` still threw an error, but I hit "debug anyway"

Could you run `$PSversionTable` in the terminal that VS Code is running and verify the version number?

![image](https://user-images.githubusercontent.com/5290572/179100787-5a4308c6-4410-456e-9dc0-ef78eb7c7cd0.png)

**Comment by nturinski** [comment]
Hi [lavibhatnagar](https://github.com/lavibhatnagar), hitting F5 does work for me and attaches to the PS trigger for me. The only other thing that I tried was having a `main.cs` file in the root of my directory. It can be an empty file.

Unfortunately, this doesn't seem like something that our extension can fix directly, but I will keep working with you to try to figure out a workaround/solution.

**Comment by lavibhatnagar** [comment]
Hi @nturinski 

i tried with creating new main.cs file in root directory. but still i am getting same error.

Are you able to make a request to function?
i can only run the code if i run the script. all other option seems not working for me,
![image](https://user-images.githubusercontent.com/5319479/179469004-ff534fe1-5002-4e49-969c-add53064e4ec.png)

**Comment by adrwh** [comment]
For me, I can run "func host start" manually and get function output, but i cannot use breakpoints.  If i try to run F5, i get ugly error messages `Result: ERROR: Unable to find type [HttpStatusCode]`, which sounds like it cannot load the underlying libraries.

**Comment by yirmio** [comment]
> Hello, the issue can be fixed by changing your default Powershell Integrated Console to version 7 in vscode settings.json: "terminal.integrated.profiles.windows": { ..... "Powershell 7":{ "path": "C:\Program Files\PowerShell\7\pwsh.exe", "icon": "terminal-powershell" } }, "terminal.integrated.defaultProfile.windows": "Powershell 7",

This one is not working for me....

**Comment by lavibhatnagar** [comment]
> > Hello, the issue can be fixed by changing your default Powershell Integrated Console to version 7 in vscode settings.json: "terminal.integrated.profiles.windows": { ..... "Powershell 7":{ "path": "C:\Program Files\PowerShell\7\pwsh.exe", "icon": "terminal-powershell" } }, "terminal.integrated.defaultProfile.windows": "Powershell 7",
> 
> This one is not working for me....

Same here not working for me either

**Comment by kteamkay** [comment]
> > > Hello, the issue can be fixed by changing your default Powershell Integrated Console to version 7 in vscode settings.json: "terminal.integrated.profiles.windows": { ..... "Powershell 7":{ "path": "C:\Program Files\PowerShell\7\pwsh.exe", "icon": "terminal-powershell" } }, "terminal.integrated.defaultProfile.windows": "Powershell 7",
> > 
> > 
> > This one is not working for me....
> 
> Same. Not working for me either

Have you installed PS7?
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2

**Comment by allanreyes** [comment]
Installing .Net Core 3.1, x86 worked for me:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-3.1.29-windows-x86-installer

**Comment by yirmio** [comment]
> > > > Hello, the issue can be fixed by changing your default Powershell Integrated Console to version 7 in vscode settings.json: "terminal.integrated.profiles.windows": { ..... "Powershell 7":{ "path": "C:\Program Files\PowerShell\7\pwsh.exe", "icon": "terminal-powershell" } }, "terminal.integrated.defaultProfile.windows": "Powershell 7",
> > > 
> > > 
> > > This one is not working for me....
> > 
> > 
> > Same. Not working for me either
> 
> Have you installed PS7? https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2

yes.....

**Comment by gammelgaard52** [comment]
What fixed the problem for me, was to install this:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.29-windows-x64-installer

It's important that it's the Desktop version - other versions did NOT solve the problem.

**Comment by misteriks** [comment]
> Hello, the issue can be fixed by changing your default Powershell Integrated Console to version 7 in vscode settings.json: "terminal.integrated.profiles.windows": { ..... "Powershell 7":{ "path": "C:\Program Files\PowerShell\7\pwsh.exe", "icon": "terminal-powershell" } }, "terminal.integrated.defaultProfile.windows": "Powershell 7",

I also had to update "powershell.powerShellDefaultVersion"  from "Windows PowerShell (x64)" to "Windows PowerShell"

**Comment by lavibhatnagar** [comment]
I have installed dot net runtime windows installer (x64) and also updated PS 7 veriosn to the latest, and it did fixed the issue.

Thanks @gammelgaard52 @kteamkay 

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.29-windows-x64-installer

**Comment by davidobrien1985** [comment]
same issue for me, and nothing here works.
PowerShell 7.2
PowerShell v4 Function

Same error. The function host starts. grpc error comes up, VS Code debugger doesn't attach.

**Comment by cemmetje87** [comment]
I was able to resolve this to update extensionBundle in host.josn to:
{
"version": "2.0",
"extensionBundle": {
"id": "Microsoft.Azure.Functions.ExtensionBundle",
"version": "**[3.3.0, 4.0.0)**"
}
}

After restarting VSCode it worked again

**Comment by nturinski** [comment]
> I was able to resolve this to update extensionBundle in host.josn to: { "version": "2.0", "extensionBundle": { "id": "Microsoft.Azure.Functions.ExtensionBundle", "version": "**[3.3.0, 4.0.0)**" } }
> 
> After restarting VSCode it worked again

Can anyone else confirm that updating the extension bundle resolves the issue for them?
