### ISSUE TITLE
"Signature: PackageIsUnreadable" error when attempting to install extension

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [microsoft/vscode-azurefunctions#3606]
## Current editor / operating system information:

Version: 1.77.0-insider
Commit: 155cd6db223feb1f8c734ca70e108b9efec7b054
Date: 2023-03-02T12:46:14.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: Yes

## Steps to reproduce:

1. Open the extensions tab
2. Click the Install button 

## Errors

Here's the relevant log messages:

```
2023-03-02 15:38:05.570 [info] Getting Manifest... ms-azuretools.vscode-azurefunctions
2023-03-02 15:38:06.160 [info] Installing extension: ms-azuretools.vscode-azurefunctions
2023-03-02 15:38:06.592 [info] Getting Manifest... ms-vscode.azure-account
2023-03-02 15:38:07.170 [info] Getting Manifest... ms-azuretools.vscode-azureresourcegroups
2023-03-02 15:38:07.372 [info] Installing extension: ms-vscode.azure-account ms-azuretools.vscode-azurefunctions
2023-03-02 15:38:07.373 [info] Installing extension: ms-azuretools.vscode-azureresourcegroups ms-azuretools.vscode-azurefunctions
2023-03-02 15:38:08.419 [error] Error while installing the extension: ms-vscode.azure-account
2023-03-02 15:38:08.423 [error] Failed to install extension. ms-azuretools.vscode-azurefunctions
2023-03-02 15:38:08.424 [error] Signature: PackageIsUnreadable
    at ki.download (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:468)
    at async Q.x (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:20769)
    at async Q.h (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:18910)
2023-03-02 15:38:09.431 [error] Signature: PackageIsUnreadable
    at ki.download (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:468)
    at async Q.x (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:20769)
    at async Q.h (/vscode/vscode-server-insiders/bin/linux-x64/155cd6db223feb1f8c734ca70e108b9efec7b054-insider/out/vs/server/node/server.main.js:153:18910)
```

**Comment by MicroFish91** [comment]
I see that you're running VS Code-Insiders, could you please try reproducing this with the VS Code stable release and let us know if it resolves your issue?  We suspect this is related to the Insiders update.
