### ISSUE TITLE
Doesn't work on node v11

### ISSUE THREAD

**Issue by andig** [Microsoft/vscode-azurefunctions#887]
Trying to debug on OSX with core tools installed globally via npm this is in the debug console:

````
LanguageWorkerConsoleLog[error] Node.js version is too low. The version you are using is v11.4.0, but the runtime requires an Active LTS or Current version (ex: 8.11.1 or 10.6.0). For deployed code, change WEBSITE_NODE_DEFAULT_VERSION in App Settings. Locally, upgrade the node version used by your machine (make sure to quit and restart your code editor to pick up the changes).
nodejsWorker.js:35
Error: "Node.js version is too low. The version you are using is v11.4.0, but the runtime requires an Active LTS or Current version (ex: 8.11.1 or 10.6.0). For deployed code, change WEBSITE_NODE_DEFAULT_VERSION in App Settings. Locally, upgrade the node version used by your machine (make sure to quit and restart your code editor to pick up the changes)."
nodejsWorker.js:36
    at validateNodeVersion (file:///usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/node/dist/src/nodejsWorker.js:36:8)
    at (anonymous) (file:///usr/local/lib/node_modules/azure-functions-core-tools/bin/workers/node/dist/src/nodejsWorker.js:39:0)
    at Module._compile (internal/modules/cjs/loader.js:723:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:734:9)
````

Looks like a broken version comparison?

**Comment by EricJizbaMSFT** [comment]
It looks like the functions team re-worded this error here: https://github.com/Azure/azure-functions-nodejs-worker/pull/153. Instead of "Node.js version is too low", they say "Incompatible Node.js version" (They don't support v11). Closing this as external - if you have any other suggestions on the wording of the error message I recommend filing an issue directly in their repo: https://github.com/Azure/azure-functions-nodejs-worker/issues
